---
abstract: 'Mount a directory with templates.'
author:
  - 'Jan Henning Thorsen'
build_requires:
  DBD::SQLite: 1
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
  Test::Pod: 1.2
  Test::Pod::Coverage: 1
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fuse-Template
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::MOP::Object: 1.03
  DBIx::Class::Schema::Loader: 0.07
  Fuse: 0.09
  Moose: 1.07
  MooseX::Getopt: 0.26
  MooseX::Types: 0.21
  Template: 2
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Fuse-Template
  homepage: http://search.cpan.org/dist/Fuse-Template
  license: http://dev.perl.org/licenses/
  repository: git://github.com//home/repositories/fuse-template.git
version: 0.0201
