---
abstract: 'Mount a directory with templates.'
author:
  - 'Jan Henning Thorsen'
build_requires:
  DBD::SQLite: 1
  ExtUtils::MakeMaker: 6.42
  File::Find: 1
  Test::More: 0.8
  Test::Pod: 1.2
  Test::Pod::Coverage: 1
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fuse-Template
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  DBIx::Class: 0.08
  DBIx::Class::Schema::Loader: 0.04
  Fuse: 0.09
  Moose: 0.8
  MooseX::Getopt: 0.2
  MooseX::Types: 0.16
  Template: 2
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
